---
- hosts: localhost
  tasks:
    - name: Pull-app
      docker_container:
        name: my-app
        image: thoratshubham/portfolio:latest
        state: started
        detach: yes
        ports:
        - "80:8000"
  